name = "Enhanced Soundscape Plus"
prefix = "ESSP"
author = "ThomasAngel"
template = "cba"
mainprefix = "x"
[files]
include = [
    "LICENSE",
    "mod.cpp",
    "README.md"
]
folder_optionals = false
sig_version = 3

[version]
path = "addons/core/script_version.hpp"
